#
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the cm71xx_auth module
"""


class AuthArgs(object):  # pylint: disable=R0903
    """The arg spec for the cm71xx_auth module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'auth_type': {'type': 'str'},
                        'ldap': {'options': {'base_dn': {'type': 'str'},
                                             'bind_dn': {'type': 'str'},
                                             'bind_password': {'type': 'str'},
                                             'ca_cert': {'type': 'str'},
                                             'group_membership_attr': {'type': 'str'},
                                             'ignore_ssl_errors': {'type': 'bool'},
                                             'protocol': {'choices': ['ldaps_preferred',
                                                                      'ldaps_only',
                                                                      'ldap_only'],
                                                          'default': 'ldaps_preferred',
                                                          'type': 'str'},
                                             'server': {'type': 'str'},
                                             'username_attr': {'type': 'str'}},
                                 'type': 'dict'},
                        'radius': {'options': {'acct_server': {'type': 'str'},
                                               'auth_server': {'type': 'str'},
                                               'password': {'type': 'str'}},
                                   'type': 'dict'},
                        'tacas': {'options': {'auth_method': {'type': 'str'},
                                              'auth_server': {'type': 'str'},
                                              'service': {'type': 'str'}},
                                  'type': 'dict'},
                        'use_remote_groups': {'type': 'bool'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
